# Development overrides for docker-compose
# This file is automatically loaded by docker-compose

version: '3.8'

services:
  api:
    # Enable hot reload for development
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    # Restart policy for development
    restart: unless-stopped

  frontend:
    # Enable hot reload for frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development

  postgres:
    # Expose PostgreSQL for direct access during development
    ports:
      - "5432:5432"
    # More verbose logging for development
    command: postgres -c log_statement=all -c log_duration=on