site_name: CodeDox Documentation
site_url: https://chriswritescode-dev.github.io/codedox
repo_url: https://github.com/chriswritescode-dev/codedox
repo_name: codedox

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - toc.follow

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Features:
    - Web UI: features/webui.md
    - Web Crawling: features/crawling.md
    - Code Extraction: features/extraction.md
    - Search: features/search.md
    - MCP Integration: features/mcp.md
  - API Reference:
    - REST API: api/rest.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chriswritescode-dev/codedox